# Site settings
title: Ben Wilhelm
email: benjamin.m.wilhelm@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Web developer and sometime theatrical lighting designer living in Chicago, IL.

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://benwilhelm.com" # the base hostname & protocol for your site
github_username:  benwilhelm



# Build settings
markdown: kramdown

permalink: pretty

highligher: pygments

cdn_path: https://dl.dropboxusercontent.com/u/8637739/benwilhelm.com

category_archive:
  path: category
  layout: category_archive
  slugify: true



# Environment-specific settings
env: development
drafts: true #this setting is overridden in the grunt-jekyll task
# limit_posts: 5
